from pymongo import MongoClient

WTF_CSRF_ENABLED = True
SECRET_KEY = 'Put your secret key here'
DB_NAME = 'proDB'
DB_NAME_CRAWLER = 'crawlerDB'
ip='127.0.0.1'
# ip = '13.126.57.117'
# ip = '35.154.116.6' #repupro instance public IP
port=27017
DATABASE = MongoClient(ip,port)[DB_NAME]
DATABASE_CRAWLER = MongoClient(ip,port)[DB_NAME_CRAWLER]


REGISTEREDUSERS_COLLECTION = DATABASE.registeredUsers
HOTEL_COLLECTION = DATABASE.hotelData
RESTAURANT_COLLECTION = DATABASE.restaurantData
SOCIALMEDIADATA_COLLECTION = DATABASE.socialMediaData
TICKET_COLLECTION = DATABASE.ticketData
REPLYCREDENTIALS_COLLECTION = DATABASE.replyLoginCredentials
ZOMATO_ENTITYID_COLLECTION = DATABASE.zmEntityId
DEPTHOTEL_COLLECTION = DATABASE.departmentHeadsHotel
DEPTRESTAURANT_COLLECTION = DATABASE.departmentHeadsRestaurant
SAVEDEMAILDATA_COLLECTION = DATABASE.savedEmailData
SMSDATA_COLLECTION = DATABASE.smsData
REPLIES_COLLECTION = DATABASE.replies

COUNTRY_COLLECTION = DATABASE_CRAWLER.countries
STATE_COLLECTION = DATABASE_CRAWLER.states
CITY_COLLECTION = DATABASE_CRAWLER.city
AREAS_COLLECTION = DATABASE_CRAWLER.area
SOURCES_COLLECTION = DATABASE_CRAWLER.sources
PROPERTY_COLLECTION = DATABASE_CRAWLER.properties
SEQUENCE_COLLECTION = DATABASE_CRAWLER.seqs

FB_TOKEN = "342093956136947|QD8JqM4FAjErakLAi6EtCkaquqE"
MSG_TOKEN = "131640AnPUovS0ZQU5832b5b2"

DEBUG = True
